/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 03-feb.-2018 18:36:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Drop Tables */

DROP TABLE IF EXISTS usuario CASCADE
;

/* Create Tables */

CREATE TABLE usuario
(
	nombre varchar(100) NOT NULL,
	alias varchar(50) NOT NULL,
	contrasenia varchar(50) NOT NULL,
	nivel varchar(50) NOT NULL,
	estado boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE usuario ADD CONSTRAINT PK_usuario
	PRIMARY KEY (alias)
;
